services:
  db:
    image: postgres:15-alpine
    container_name: policies_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: suprith
      POSTGRES_DB: policies_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./Agent-backend
    container_name: backend
    restart: always
    env_file:
      - ./Agent-backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./Health-Agent-dashboard
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
